on: [push]
name: AzureARMDeploy

jobs:

  executesample:
    runs-on: ubuntu-latest
    steps:
     
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - uses: azure/arm-deploy@v1
      with:        
        subscriptionId: d5147816-b002-458a-ade9-75da2183ac3e
        resourceGroupName: github-action-arm-rg 
        template: ./vmdeploy.json
